package GUI.patients;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import models.Patient;
import util.Patients;

public class DeleteUpdatePatient extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteUpdatePatient.class.getName());

    private String id = "-1";

    /**
     * Creates new form DeleteUpdate
     */
    public DeleteUpdatePatient() {
        initComponents();
    }

    public DeleteUpdatePatient(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Actualizar - Eliminar Registro");
        this.id = id;
        idDeleteInput.setText(id);
        this.setDataToUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idUpdateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        birthDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cellPhoneField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bloodTypeComboBox = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idDeleteInput = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setText("Editar Información de Paciente");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Número de Identificación Personal");

        idUpdateField.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Nombres");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Apellidos");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Sexo");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Número de Teléfono");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Correo Electrónico");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Tipo de Sangre");

        bloodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        updateBtn.setText("Actualizar");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(updateBtn)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idUpdateField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(birthDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(nameField)
                                .addComponent(cellPhoneField)
                                .addComponent(bloodTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Editar", jPanel1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Eliminar Registro");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Número de identificación personal");

        idDeleteInput.setEditable(false);

        deleteBtn.setText("Eliminar");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtn)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(idDeleteInput)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idDeleteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar el registro de este paciente?",
                "¡Advertencia!", JOptionPane.YES_NO_OPTION); // NO = 1, SI = 0

        if (option == 0) {
            Patients util = new Patients();
            boolean success = util.deleteRegister(id);
            if (success) {
                JOptionPane.showMessageDialog(null, "Se eliminó exitosamente el registro del paciente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No fue posible eliminar el registro del paciente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // Obtención de valores
        String id = idUpdateField.getText();
        String names = nameField.getText();
        String lastnames = lastnameField.getText();
        String cellphone = cellPhoneField.getText();
        String email = emailField.getText();
        String bloodType = bloodTypeComboBox.getItemAt(bloodTypeComboBox.getSelectedIndex());
        Date birthdate;

        // Verificación de longitud de campos
        if (id.length() != 13) {
            JOptionPane.showMessageDialog(null, "El número de identificación personal debe ser de 13 dígitos y sin espacios.", "Campo Incorrecto", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (names.length() > 50 | lastnames.length() > 50) {
            JOptionPane.showMessageDialog(null, "El tamaño máximo de la cadena para nombres o apellidos es de 50 carácteres contando espacios.", "Campo de Nombre o Apellido Demasiado Largo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cellphone.length() > 14) {
            JOptionPane.showMessageDialog(null, "Por favor verifica que ingresaste un número de celular con formato de Guatemala.", "Formato de Celular Incorrecto", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email.length() > 100) {
            JOptionPane.showMessageDialog(null, "Posr favor ingresa una dirección de correo electrónico más corta.", "Dirección de Correo Demasiado Larga", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificación de obligatoriedad de campos
        if (names.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese los nombres del paciente", "Nombre Vacío", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (lastnames.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese los apellidos del paciente", "Apellido Vacío", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cellphone.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa el número celular del paciente", "Celular Vacío", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificación de RegEx de número de identificación
        String regex = "^[0-9]{13}$";

        if (!(id.matches(regex))) {
            JOptionPane.showMessageDialog(null, "El número de identificación personal debe contener solamente números", "ID Incorrecto", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificación de RegEx de número celular
        regex = "^(?:\\+502 ?)?\\d{4}-?\\d{4}$";

        if (!(cellphone.matches(regex))) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número telefónico guatemalteco válido.", "Número Celular Inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtención y verificación de la fecha de nacimiento
        try {
            birthdate = birthDateChooser.getDate();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Por favor verifica que hayas ingresado correctamente la fecha de nacimiento.", "Error Inesperado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        /* 
         * Al pasar todos los filtros, se procede a la creación de un objeto Patient y su registro en archivo persitente       
         */
        // Parseo de variable de fecha
        LocalDate birthDateLD = birthdate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Setteo de Variables
        String gender;

        switch (genderComboBox.getSelectedIndex()) {
            case 0 ->
                gender = "M";
            case 1 ->
                gender = "F";
            default ->
                throw new AssertionError();
        }

        Patient patient = new Patient(id, names, lastnames, birthDateLD, gender, cellphone, email, bloodType);
        Patients util = new Patients();
        boolean success = util.updatePatient(patient);

        if (!success) {
            JOptionPane.showMessageDialog(null, "No fue posible actualizar la información del paciente. Vuelve a intentarlo.", "Error Inesperado", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(null, "Datos del paciente actualizados correctamente.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void setDataToUpdate() {
        // Obtencion de datos del id correspondiente
        Patients util = new Patients();
        Patient p = util.searchRegister(id);

        if (p == null) {
            JOptionPane.showMessageDialog(null, "No fue posible cargar la información de este paciente.", "Error Inesperado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parseo de datos tipo fecha
        Date date = Date.from(p.getBirthdate().atStartOfDay(ZoneId.systemDefault()).toInstant());

        // Parseo del campo género
        int gender = 0;
        if (p.getGender().equals("F")) {
            gender = 1;
        }

        // Parseo del campo "tipo de sangre"
        int bloodType;
        switch (p.getBloodType()) {
            case "A+" ->
                bloodType = 0;
            case "A-" ->
                bloodType = 1;
            case "B+" ->
                bloodType = 2;
            case "B-" ->
                bloodType = 3;
            case "AB+" ->
                bloodType = 4;
            case "AB-" ->
                bloodType = 5;
            case "O+" ->
                bloodType = 6;
            case "O-" ->
                bloodType = 7;
            default ->
                throw new AssertionError();
        }

        // Setteo de datos en los campos para actualizar
        idUpdateField.setText(p.getID());
        nameField.setText(p.getName());
        lastnameField.setText(p.getLastname());
        birthDateChooser.setDate(date);
        genderComboBox.setSelectedIndex(gender);
        cellPhoneField.setText(p.getCellphone());
        emailField.setText(p.getEmail());
        bloodTypeComboBox.setSelectedIndex(bloodType);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteUpdatePatient().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthDateChooser;
    private javax.swing.JComboBox<String> bloodTypeComboBox;
    private javax.swing.JTextField cellPhoneField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField idDeleteInput;
    private javax.swing.JTextField idUpdateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
