package GUI.patients;

import GUI.Home;
import GUI.Login;
import GUI.doctors.HomeDoctors;
import GUI.reports.HomeReports;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Patient;
import models.Receptionist;
import DTO.PatientsDto;
import DTO.ReportsDto;
import GUI.appointments.HomeAppointments;

public class HomePatients extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePatients.class.getName());

    Receptionist receptionist;

    /**
     * Creates new form HomePatients
     */
    public HomePatients() {
        initComponents();
    }

    // Constructor parametrizado para inyección de dependencias
    public HomePatients(String id, String fullname) {
        receptionist = new Receptionist(id, fullname, "");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Pacientes");
        this.loadTableData(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchPatientField = new javax.swing.JTextField();
        searchPatientBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        createPatientBtn = new javax.swing.JButton();
        attributeComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        filesMenu = new javax.swing.JMenu();
        homeMenu = new javax.swing.JMenu();
        appointmentMenu = new javax.swing.JMenu();
        doctorsMenu = new javax.swing.JMenu();
        reportsMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Listado de Pacientes");

        searchPatientField.addActionListener(this::searchPatientFieldActionPerformed);

        searchPatientBtn.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        searchPatientBtn.setText("Buscar");
        searchPatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchPatientBtnMouseClicked(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Fecha Nacimiento", "Sexo", "Teléfono", "Email", "Tipo Sangre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        dataTable.getTableHeader().setReorderingAllowed(false);
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setResizable(false);
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(130);
            dataTable.getColumnModel().getColumn(1).setResizable(false);
            dataTable.getColumnModel().getColumn(1).setPreferredWidth(220);
            dataTable.getColumnModel().getColumn(2).setResizable(false);
            dataTable.getColumnModel().getColumn(2).setPreferredWidth(130);
            dataTable.getColumnModel().getColumn(3).setResizable(false);
            dataTable.getColumnModel().getColumn(3).setPreferredWidth(120);
            dataTable.getColumnModel().getColumn(4).setResizable(false);
            dataTable.getColumnModel().getColumn(4).setPreferredWidth(130);
            dataTable.getColumnModel().getColumn(5).setResizable(false);
            dataTable.getColumnModel().getColumn(5).setPreferredWidth(250);
            dataTable.getColumnModel().getColumn(6).setResizable(false);
            dataTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        createPatientBtn.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        createPatientBtn.setText("Agregar Paciente");
        createPatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPatientBtnMouseClicked(evt);
            }
        });

        attributeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "No. Identificación", "Nombre", "Apellido" }));

        filesMenu.setText("Archivos");
        filesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filesMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(filesMenu);

        homeMenu.setText("Inicio");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        appointmentMenu.setText("Citas");
        appointmentMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(appointmentMenu);

        doctorsMenu.setText("Médicos");
        doctorsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(doctorsMenu);

        reportsMenu.setText("Reportes");
        reportsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(reportsMenu);

        logoutMenu.setText("Cerrar Sesión");
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(searchPatientField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(attributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchPatientBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createPatientBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchPatientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPatientBtn)
                    .addComponent(attributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPatientBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filesMenuMouseClicked
        // Verificación y creación de carpeta de reportes en caso no exista
        ReportsDto reports = new ReportsDto();
        try {
            reports.createFolder();

            // Apertura de carpeta
            reports.openFolder();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_filesMenuMouseClicked

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        // Cerrar ventana de inicio
        this.dispose();

        // Abrir ventana de página de inicio
        Home home = new Home(receptionist.getId(), receptionist.getFullName());
        home.setVisible(true);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void doctorsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMenuMouseClicked
        // Cerrar ventana de inicio
        this.dispose();

        // Abrir ventana de doctores
        HomeDoctors homeDoctors = new HomeDoctors(receptionist.getId(), receptionist.getFullName());
        homeDoctors.setVisible(true);
    }//GEN-LAST:event_doctorsMenuMouseClicked

    private void reportsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMenuMouseClicked
        // Cerrar ventana de inicio
        this.dispose();

        // Abrir ventana de reportes
        HomeReports homeReports = new HomeReports(receptionist.getId(), receptionist.getFullName());
        homeReports.setVisible(true);
    }//GEN-LAST:event_reportsMenuMouseClicked

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        // Cerrar ventana de inicio
        this.dispose();

        // Abrir ventana de login
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void searchPatientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatientFieldActionPerformed
        PatientsDto util = new PatientsDto();
        ArrayList<Patient> patients = util.searchData(searchPatientField.getText().trim(), attributeComboBox.getSelectedIndex());
        loadTableData(patients);

        if (attributeComboBox.getSelectedIndex() == 0) {
            searchPatientField.setText("");
        }
    }//GEN-LAST:event_searchPatientFieldActionPerformed

    private void searchPatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPatientBtnMouseClicked
        PatientsDto util = new PatientsDto();
        ArrayList<Patient> patients = util.searchData(searchPatientField.getText().trim(), attributeComboBox.getSelectedIndex());
        loadTableData(patients);

        if (attributeComboBox.getSelectedIndex() == 0) {
            searchPatientField.setText("");
        }
    }//GEN-LAST:event_searchPatientBtnMouseClicked

    private void createPatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPatientBtnMouseClicked
        // Abriri ventana para crear paciente
        CreatePatient createPatient = new CreatePatient(receptionist.getId(), receptionist.getFullName());
        createPatient.setVisible(true);
    }//GEN-LAST:event_createPatientBtnMouseClicked

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        if (evt.getClickCount() == 2) {
            int row = dataTable.rowAtPoint(evt.getPoint());

            if (row >= 0) {
                Object value = dataTable.getValueAt(row, 0);

                DeleteUpdatePatient duPatient = new DeleteUpdatePatient(String.valueOf(value));
                duPatient.setVisible(true);
            }
        }
    }//GEN-LAST:event_dataTableMouseClicked

    private void appointmentMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentMenuMouseClicked
        // Cerrar ventana de inicio
        this.dispose();

        // Abrir ventana de citas
        HomeAppointments homeAppointments = new HomeAppointments(receptionist.getId(), receptionist.getFullName());
        homeAppointments.setVisible(true);
    }//GEN-LAST:event_appointmentMenuMouseClicked

    // Impresión de datos en JTable
    private void loadTableData(ArrayList<Patient> dataList) {
        try {
            // Formato para mostrar fechas
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            if (dataList == null) {
                PatientsDto util = new PatientsDto();
                dataList = util.readAll();
            }

            DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
            model.setRowCount(0);

            // Centrar contenido de las celdas
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

            for (int i = 0; i < dataTable.getColumnCount(); i++) {
                dataTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

            // Llenado de tabla
            for (Patient patient : dataList) {

                // Se cambia el género de sólo su inicial al nombre completo
                if (patient.getGender().equals("M")) {
                    patient.setGender("Masculino");
                } else {
                    patient.setGender("Femenino");
                }

                model.addRow(new Object[]{
                    patient.getID(),
                    patient.getName() + " " + patient.getLastname(),
                    formatter.format(patient.getBirthdate()),
                    patient.getGender(),
                    patient.getCellphone(),
                    patient.getEmail(),
                    patient.getBloodType()
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePatients().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu appointmentMenu;
    private javax.swing.JComboBox<String> attributeComboBox;
    private javax.swing.JButton createPatientBtn;
    private javax.swing.JTable dataTable;
    private javax.swing.JMenu doctorsMenu;
    private javax.swing.JMenu filesMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenu reportsMenu;
    private javax.swing.JButton searchPatientBtn;
    private javax.swing.JTextField searchPatientField;
    // End of variables declaration//GEN-END:variables
}
