package GUI.doctors;

import DTO.DoctorsDto;
import java.time.LocalTime;
import java.util.UUID;
import javax.swing.JOptionPane;
import models.Doctor;
import models.Receptionist;

public class CreateDoctor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateDoctor.class.getName());

    Receptionist receptionist;

    /**
     * Creates new form CreateDoctor
     */
    public CreateDoctor() {
        initComponents();
    }

    // Constructor parametrizado para inyección de dependencias
    public CreateDoctor(String id, String fullname) {
        receptionist = new Receptionist(id, fullname, "");
        initComponents();
        this.generateUUID();
        this.setLocationRelativeTo(null);
        this.setTitle("Crear Doctor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        namesField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lastnamesField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        specialityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cellphoneField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hourStartField = new com.toedter.components.JSpinField();
        jLabel10 = new javax.swing.JLabel();
        minuteStartField = new com.toedter.components.JSpinField();
        daypartIndicatorStartComboBox = new javax.swing.JComboBox<>();
        hourEndField = new com.toedter.components.JSpinField();
        jLabel11 = new javax.swing.JLabel();
        minuteEndField = new com.toedter.components.JSpinField();
        daypartIndicatorEndComboBox = new javax.swing.JComboBox<>();
        createRegisterBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Crear Doctor");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel2.setText("ID");

        idField.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel3.setText("Nombres");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel4.setText("Apellidos");

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel5.setText("Especialidad");

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel6.setText("Celular");

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel7.setText("Correo Electrónico");

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel8.setText("Hora de Inicio de Atención");

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel9.setText("Hora de Fin de Atención");

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel10.setText(":");

        daypartIndicatorStartComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel11.setText(":");

        daypartIndicatorEndComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        createRegisterBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createRegisterBtn.setText("Crear Registro");
        createRegisterBtn.addActionListener(this::createRegisterBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cellphoneField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lastnamesField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(idField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hourStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minuteStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daypartIndicatorStartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hourEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minuteEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daypartIndicatorEndComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(createRegisterBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(namesField)
                                    .addComponent(specialityField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(emailField))))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(minuteStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daypartIndicatorStartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(minuteEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daypartIndicatorEndComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createRegisterBtn)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRegisterBtnActionPerformed
        // Obtención de valores
        String id = idField.getText().trim();
        String names = namesField.getText().trim();
        String lastnames = lastnamesField.getText().trim();
        String speciality = specialityField.getText().trim();
        String cellphone = cellphoneField.getText().trim();
        String email = emailField.getText().trim();

        int startHourShift;
        int startMinuteShift;
        String startShiftDaypartIndicator;

        int endHourShift;
        int endMinuteShift;
        String endShiftDaypartIndicator;

        try {
            // Obtención de valores de hora de inicio de turno
            startHourShift = hourStartField.getValue();
            startMinuteShift = minuteStartField.getValue();
            startShiftDaypartIndicator = daypartIndicatorStartComboBox.getItemAt(daypartIndicatorStartComboBox.getSelectedIndex());

            // Obtención de valores de hora de finalización de turno
            endHourShift = hourEndField.getValue();
            endMinuteShift = minuteEndField.getValue();
            endShiftDaypartIndicator = daypartIndicatorEndComboBox.getItemAt(daypartIndicatorEndComboBox.getSelectedIndex());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Por favor, ingrese datos numéricos en los campos de horas y minutos", "Información Inválida", JOptionPane.ERROR_MESSAGE);
            return;
        }

        /*
         * Verificación de longitud de campos
         */
        // Nombres o apellidos
        if (names.length() > 50 | lastnames.length() > 50) {
            JOptionPane.showMessageDialog(null, "El tamaño máximo de la cadena para nombres o apellidos es de 50 carácteres, contando espacios.", "Campo de Nombre o Apellido Demasiado Largo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Especialidad
        if (speciality.length() > 50) {
            JOptionPane.showMessageDialog(null, "El tamaño máximo de la cadena para una especialidad es de 50 carácteres, contando espacios.", "Nombre de Especialidad Demasiado Largo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Celular
        if (cellphone.length() > 14) {
            JOptionPane.showMessageDialog(null, "Por favor verifica que ingresaste un número de celular con formato de Guatemala.", "Formato de Celular Incorrecto", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Correo electrónico
        if (email.length() > 100) {
            JOptionPane.showMessageDialog(null, "Posr favor ingresa una dirección de correo electrónico más corta.", "Dirección de Correo Demasiado Larga", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificación de obligatoriedad de campos
        // Nombres
        if (names.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese los nombres del doctor", "Nombre Vacío", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Apellidos
        if (lastnames.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese los apellidos del doctor", "Apellido Vacío", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Especialidad
        if (speciality.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la especialidad del doctor.", "Especialidad Faltante", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Celular
        if (cellphone.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa el número celular del paciente", "Celular Vacío", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificación de RegEx de número celular
        String regex = "^(?:\\+502 ?)?\\d{4}-?\\d{4}$";

        if (!(cellphone.matches(regex))) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número telefónico guatemalteco válido.", "Número Celular Inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalTime finalHourStart;
        LocalTime finalHourEnd;

        // Armado y verificación de horas de turno
        try {
            if (startHourShift < 1 || startHourShift > 12 || endHourShift < 1 || endHourShift > 12) {
                JOptionPane.showMessageDialog(null, "Solamente es posible ingresar horas en un rango de 1 - 12.", "Hora Inválida", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (startMinuteShift < 0 || startMinuteShift > 59 || endMinuteShift < 0 || endMinuteShift > 59) {
                JOptionPane.showMessageDialog(null, "Solamente es posible ingresar minutos en un rango de 00 - 59.", "Minutos Inválidos", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Parseo de int a LocalTime del inicio del turno
            int hour24 = startHourShift;

            if ("PM".equals(startShiftDaypartIndicator) && startHourShift < 12) {
                hour24 += 12;
            } else if ("AM".equals(startShiftDaypartIndicator) && startHourShift == 12) {
                hour24 = 0;
            }

            finalHourStart = LocalTime.of(hour24, startMinuteShift);

            // Parseo de int a LocalTime del fin del turno
            hour24 = endHourShift;

            if ("PM".equals(endShiftDaypartIndicator) && endHourShift < 12) {
                hour24 += 12;
            } else if ("AM".equals(endShiftDaypartIndicator) && endHourShift == 12) {
                hour24 = 0;
            }

            finalHourEnd = LocalTime.of(hour24, endMinuteShift);            
            
            if (finalHourEnd.isBefore(finalHourStart)) {
                JOptionPane.showMessageDialog(null, "El turno del médico no puede terminar antes que inicie.", "Horario Inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No fue posible almacenar el horario de inicio y fin de turno del doctor. Por favor verifica que hayas ingresado datos válidos.", "Error Inesperado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        /*
         * Al pasar todos los filtros, se procede a la creación de un objeto Doctor y su registro en archivo persistente
         */
        // Declaración de registro como "activo"
        boolean status = true;

        Doctor doctor = new Doctor(id, names, lastnames, speciality, cellphone, email, finalHourStart, finalHourEnd, status);
        DoctorsDto util = new DoctorsDto();
        boolean success = util.writeRegister(doctor);

        if (!success) {
            JOptionPane.showMessageDialog(null, "No fue posible registrar la información del doctor. Vuelve a intentarlo.", "Error Inesperado", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(null, "Datos del doctor registrados correctamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_createRegisterBtnActionPerformed

    private void generateUUID() {
        UUID tempId = UUID.randomUUID();
        String id = tempId.toString();

        idField.setText(id);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateDoctor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cellphoneField;
    private javax.swing.JButton createRegisterBtn;
    private javax.swing.JComboBox<String> daypartIndicatorEndComboBox;
    private javax.swing.JComboBox<String> daypartIndicatorStartComboBox;
    private javax.swing.JTextField emailField;
    private com.toedter.components.JSpinField hourEndField;
    private com.toedter.components.JSpinField hourStartField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnamesField;
    private com.toedter.components.JSpinField minuteEndField;
    private com.toedter.components.JSpinField minuteStartField;
    private javax.swing.JTextField namesField;
    private javax.swing.JTextField specialityField;
    // End of variables declaration//GEN-END:variables
}
