package GUI;

import java.io.RandomAccessFile;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.Receptionist;

public class Login extends javax.swing.JFrame {

    // Variables globales
    private ArrayList<Receptionist> receptionists = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio de Sesión");
        retrieveData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Inicio de Sesión");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Bienvenido al sistema de control de datos de la clínca.");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setText("Por favor ingrese su contraseña.");

        passwordField.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        passwordField.addActionListener(this::passwordFieldActionPerformed);

        loginBtn.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        loginBtn.setText("Iniciar Sesión");
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(579, 579, 579)
                .addComponent(loginBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(551, 551, 551)
                .addComponent(jLabel1)
                .addContainerGap(552, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        this.checkPassword();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        this.checkPassword();
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void retrieveData() {
        try {
            final int idSize = 36;
            final int fullNameSize = 16;
            final int passwordSize = 2;

            receptionists.clear();
            RandomAccessFile raf = new RandomAccessFile("data/roles.dat", "r");

            while (raf.getFilePointer() < raf.length()) {
                if (raf.getFilePointer() + idSize + fullNameSize + passwordSize > raf.length()) {
                    break;
                }

                byte[] idData = new byte[idSize];
                byte[] fullNameData = new byte[fullNameSize];
                byte[] passwordData = new byte[passwordSize];

                // Lectura de campos
                raf.readFully(idData);
                raf.readFully(fullNameData);
                raf.readFully(passwordData);

                // Manejo de fin de línea (\n o \r\n)
                if (raf.getFilePointer() < raf.length()) {
                    byte b = raf.readByte();
                    if (b == '\r' && raf.getFilePointer() < raf.length()) {
                        long mark = raf.getFilePointer();
                        if (raf.readByte() != '\n') {
                            raf.seek(mark);
                        }
                    }
                }

                // Parse de datos binarios a string
                String id = new String(idData, StandardCharsets.ISO_8859_1).trim();
                String fullname = new String(fullNameData, StandardCharsets.ISO_8859_1).trim();
                String password = new String(passwordData, StandardCharsets.ISO_8859_1).trim();

                if (!id.isEmpty()) {
                    receptionists.add(new Receptionist(id, fullname, password));
                }
            }
            raf.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void checkPassword() {
        try {
            String password = new String(passwordField.getPassword());

            if (password.isBlank()) {
                return;
            }

            for (Receptionist receptionist : receptionists) {
                if (receptionist != null && receptionist.getPassword().equals(password)) {
                    DTO.ReportsDto.recordLog(receptionist.getFullName() + " (" + receptionist.getId() + ")",
                            "Autenticación / Sistema", "Login / Logout", "Inicio de sesión de usuario en el sistema");
                    this.dispose();
                    Home home = new Home(receptionist.getId(), receptionist.getFullName());
                    home.setVisible(true);
                    return;
                }
            }

            JOptionPane.showMessageDialog(null, "Por favor vuelva a intentarlo.", "Contraseña Incorrecta", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            e.getMessage();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
